import{a as y}from"./assets/vendor-BbYF_8OW.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const a=document.querySelector(".backdrop-header"),u=document.querySelector(".js-toggle-menu"),m=u.querySelector(".menu-icon"),v=document.querySelector(".js-logo-icon use"),g=()=>{const e=window.innerWidth>=768?"/img/header/icons-header.svg#icon-header-logo":"/img/header/icons-header.svg#icon-header-logo-mobile";v.setAttribute("href",e)};u.addEventListener("click",()=>{const e=a.classList.toggle("is-open");m.setAttribute("href",e?"/img/header/icons-header.svg#icon-header-close-menu":"/img/header/icons-header.svg#icon-header-open-menu")});document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",r=>{r.preventDefault();const o=e.getAttribute("href").substring(1),n=document.getElementById(o);n&&n.scrollIntoView({behavior:"smooth",block:"start"}),a.classList.contains("is-open")&&(a.classList.remove("is-open"),m.setAttribute("href","/img/header/icons-header.svg#icon-header-open-menu"))})});window.addEventListener("resize",g);window.addEventListener("DOMContentLoaded",g);const b="https://sound-wave.b.goit.study/api",w="/artists";function h(e=1){const r={limit:8,page:e};return y.get(`${b}${w}`,{params:r}).then(o=>o.data).catch(o=>{throw console.error("Error fetching artists:",o),o})}const d=document.querySelector(".load-more-btn");function E({_id:e,genres:r,strArtist:o,strBiographyEN:n,strArtistThumb:t}){return`<li class="artists-item">
        <img class="artists-img" src="${t}" alt="${o}" width="288"/>
        <ul class="artists-genres">${r.map(s=>`<li class="artists-genres-item"><p class="artists-genres-text">${s}</p></li>`).join(`
`)}</ul>
                  <h3 class="artsits-name">${o}</h3>
        <p class="artists-descr">${n}</p>
        <button class="learn-btn" type="button" id="${e}">Learn More<svg class="learn-more-svg" width="24" height="24">
        <use href="/img/sprite.svg#icon-triangle-right"></use>
      </svg></button>
      </li>`}function f(e){return e.map(E).join(`
`)}function A(){d.classList.remove("hidden")}function M(){d.classList.add("hidden")}function p(e,r){if(e<r){A();return}else M()}d.addEventListener("click",S);let i=1,l=1;const L=document.querySelector(".artists-gallery");h(i).then(e=>{const r=f(e.artists);l=Math.ceil(e.totalArtists/e.limit),L.insertAdjacentHTML("beforeend",r),p(i,l)});function S(){i++,h(i).then(e=>{const r=f(e.artists);L.insertAdjacentHTML("beforeend",r),p(i,l)})}
//# sourceMappingURL=index.js.map
